background = #1f2430
foreground = #cccac2
cursor-color = #cccac2
cursor-text = #1f2430
selection-background = #323844
selection-foreground = #cccac2

palette = 0=#1f2430
palette = 1=#f28779
palette = 2=#d5ff80
palette = 3=#ffd173
palette = 4=#73d0ff
palette = 5=#d4bfff
palette = 6=#95e6cb
palette = 7=#cccac2
palette = 8=#4a5059
palette = 9=#ffad66
palette = 10=#d5ff80
palette = 11=#ffd173
palette = 12=#73d0ff
palette = 13=#d4bfff
palette = 14=#95e6cb
palette = 15=#f3f4f5
