background = #0a0920
foreground = #606bac
cursor-color = #606bac
cursor-text = #0a0920
selection-background = #23255a
selection-foreground = #606bac

palette = 0=#0a0920
palette = 1=#f768a3
palette = 2=#a2faa8
palette = 3=#f7d668
palette = 4=#258fc4
palette = 5=#c368f7
palette = 6=#a2faf0
palette = 7=#606bac
palette = 8=#333773
palette = 9=#f78968
palette = 10=#a2faa8
palette = 11=#f7d668
palette = 12=#258fc4
palette = 13=#c368f7
palette = 14=#a2faf0
palette = 15=#9aaae5
