background = #343d46
foreground = #dfe1e8
cursor-color = #dfe1e8
cursor-text = #343d46
selection-background = #65737e
selection-foreground = #dfe1e8

palette = 0=#343d46
palette = 1=#cc6666
palette = 2=#b5bd68
palette = 3=#f0c674
palette = 4=#81a2be
palette = 5=#b294bb
palette = 6=#8abeb7
palette = 7=#dfe1e8
palette = 8=#a7adba
palette = 9=#de935f
palette = 10=#b5bd68
palette = 11=#f0c674
palette = 12=#81a2be
palette = 13=#b294bb
palette = 14=#8abeb7
palette = 15=#ffffff
