background = #0b0e14
foreground = #e6e1cf
cursor-color = #e6e1cf
cursor-text = #0b0e14
selection-background = #202229
selection-foreground = #e6e1cf

palette = 0=#0b0e14
palette = 1=#f07178
palette = 2=#aad94c
palette = 3=#ffb454
palette = 4=#59c2ff
palette = 5=#d2a6ff
palette = 6=#95e6cb
palette = 7=#e6e1cf
palette = 8=#3e4b59
palette = 9=#ff8f40
palette = 10=#aad94c
palette = 11=#ffb454
palette = 12=#59c2ff
palette = 13=#d2a6ff
palette = 14=#95e6cb
palette = 15=#f2f0e7
