background = #0f0f0f
foreground = #cacaca
cursor-color = #cacaca
cursor-text = #0f0f0f
selection-background = #262626
selection-foreground = #cacaca

palette = 0=#0f0f0f
palette = 1=#ac8a8c
palette = 2=#8aac8b
palette = 3=#aca98a
palette = 4=#8f8aac
palette = 5=#ac8aac
palette = 6=#8aabac
palette = 7=#cacaca
palette = 8=#393939
palette = 9=#ceb188
palette = 10=#8aac8b
palette = 11=#aca98a
palette = 12=#8f8aac
palette = 13=#ac8aac
palette = 14=#8aabac
palette = 15=#f0f0f0
