background = #ffffff
foreground = #343b43
cursor-color = #343b43
cursor-text = #ffffff
selection-background = #acb6c0
selection-foreground = #343b43

palette = 0=#ffffff
palette = 1=#702c00
palette = 2=#032563
palette = 3=#956400
palette = 4=#622cbc
palette = 5=#a0111f
palette = 6=#024c1a
palette = 7=#343b43
palette = 8=#88929d
palette = 9=#023b95
palette = 10=#032563
palette = 11=#956400
palette = 12=#622cbc
palette = 13=#a0111f
palette = 14=#024c1a
palette = 15=#0e1116
