background = #fffdfb
foreground = #636363
cursor-color = #636363
cursor-text = #fffdfb
selection-background = #f2e6d4
selection-foreground = #636363

palette = 0=#fffdfb
palette = 1=#df7f78
palette = 2=#50b584
palette = 3=#9ca748
palette = 4=#61a3e6
palette = 5=#a48fe1
palette = 6=#00b3c2
palette = 7=#636363
palette = 8=#cecece
palette = 9=#ce9042
palette = 10=#50b584
palette = 11=#9ca748
palette = 12=#61a3e6
palette = 13=#a48fe1
palette = 14=#00b3c2
palette = 15=#181b1f
