background = #feffff
foreground = #5a496e
cursor-color = #5a496e
cursor-text = #feffff
selection-background = #bdb6c5
selection-foreground = #5a496e

palette = 0=#feffff
palette = 1=#f80059
palette = 2=#5bb66a
palette = 3=#bd9701
palette = 4=#5ba2b6
palette = 5=#8f6c97
palette = 6=#47f9f5
palette = 7=#5a496e
palette = 8=#9c92a8
palette = 9=#bd0152
palette = 10=#5bb66a
palette = 11=#bd9701
palette = 12=#5ba2b6
palette = 13=#8f6c97
palette = 14=#47f9f5
palette = 15=#190134
