background = #1f1c16
foreground = #faf0e6
cursor-color = #faf0e6
cursor-text = #1f1c16
selection-background = #47443f
selection-foreground = #faf0e6

palette = 0=#1f1c16
palette = 1=#e87777
palette = 2=#8cb870
palette = 3=#eac67a
palette = 4=#7fa8d4
palette = 5=#b094cc
palette = 6=#6ab8b0
palette = 7=#faf0e6
palette = 8=#b8a48c
palette = 9=#da9050
palette = 10=#8cb870
palette = 11=#eac67a
palette = 12=#7fa8d4
palette = 13=#b094cc
palette = 14=#6ab8b0
palette = 15=#fef4e4
