background = #1d1d1d
foreground = #c4cbcf
cursor-color = #c4cbcf
cursor-text = #1d1d1d
selection-background = #373737
selection-foreground = #c4cbcf

palette = 0=#1d1d1d
palette = 1=#f07c82
palette = 2=#b2cf87
palette = 3=#f4ce69
palette = 4=#8fb2c9
palette = 5=#be9db9
palette = 6=#b0d5df
palette = 7=#c4cbcf
palette = 8=#918072
palette = 9=#f4a83a
palette = 10=#b2cf87
palette = 11=#f4ce69
palette = 12=#8fb2c9
palette = 13=#be9db9
palette = 14=#b0d5df
palette = 15=#fffef9
