background = #0f0b05
foreground = #c3a983
cursor-color = #c3a983
cursor-text = #0f0b05
selection-background = #2a2012
selection-foreground = #c3a983

palette = 0=#0f0b05
palette = 1=#a88c62
palette = 2=#dec8a7
palette = 3=#dec8a7
palette = 4=#c3a983
palette = 5=#a88c62
palette = 6=#dec8a7
palette = 7=#c3a983
palette = 8=#57462c
palette = 9=#dec8a7
palette = 10=#dec8a7
palette = 11=#dec8a7
palette = 12=#c3a983
palette = 13=#a88c62
palette = 14=#dec8a7
palette = 15=#231b0e
