background = #cabda0
foreground = #382e1b
cursor-color = #382e1b
cursor-text = #cabda0
selection-background = #af9f7d
selection-foreground = #382e1b

palette = 0=#cabda0
palette = 1=#382e1b
palette = 2=#110e06
palette = 3=#110e06
palette = 4=#251e0f
palette = 5=#382e1b
palette = 6=#110e06
palette = 7=#382e1b
palette = 8=#645538
palette = 9=#110e06
palette = 10=#110e06
palette = 11=#110e06
palette = 12=#251e0f
palette = 13=#382e1b
palette = 14=#110e06
palette = 15=#bcad8c
