[[items]]
path = "https://github.com/tinted-theming/tinted-shell"
name = "tinted-shell"
themes-dir = "scripts"
supported-systems = ["base16", "base24"]
hook = "source $TINTY_THEME_FILE_PATH"

[[items]]
path = "~/.dotfiles/themes/tinted-ghostty"
name = "tinted-ghostty"
themes-dir = "themes"
supported-systems = ["base16"]
