#!/bin/bash
TINTY_FILE="$HOME/.local/share/tinted-theming/tinty/tinted-sketchybar-themes-file.sh"
[ -f "$TINTY_FILE" ] && source "$TINTY_FILE"

options=(
  style=round
  width=6.0
  hidpi=on
  active_color="${SBAR_BLUE:-0xff89b4fa}"
  inactive_color="${SBAR_SELECTION:-0xff313244}"
  background_color=0x00000000
)
borders "${options[@]}"
